# Generated by Django 6.0.3 on 2026-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='no',
            new_name='account',
        ),
    ]
