# Generated by Django 6.0.3 on 2026-04-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', models.CharField(blank=True, max_length=300, null=True)),
                ('intro', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('add_time', models.DateField(auto_now_add=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.people')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
