# Generated by Django 6.0.3 on 2026-04-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_name_article_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disable',
            field=models.BooleanField(default=False, verbose_name='是否禁用'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
